[workspace]
members = [
    "libsignal-service",
    "libsignal-service-actix",
]


[patch."https://github.com/Michael-F-Bryan/libsignal-protocol-rs.git"]
libsignal-protocol = { path = "../libsignal-protocol-rs/libsignal-protocol" }
